### ISSUE TITLE
Please include COPYING file and fix header

### ISSUE THREAD

**Issue by landgraf** [alire-project/xmlezout#2]
Header says:

`
-- The  McKae   software  utilities   are  free  software;   you  can --
-- redistribute it  and/or modify it  under terms of the  GNU General --
-- Public  License  as published  by  the  Free Software  Foundation; --
-- either version  2, or (at  your option) any later  version.  McKae --
-- Software Utilities are  distributed in the hope that  they will be --
-- useful,  but  WITHOUT  ANY  WARRANTY;  without  even  the  implied --
-- warranty of  MERCHANTABILITY or FITNESS FOR  A PARTICULAR PURPOSE. --
-- See the GNU  General Public License for more  details.  You should --
-- have received a copy of the GNU General Public License distributed --
-- with DTraq; see file COPYING.   If not, write to the Free Software --
-- Foundation, 59  Temple Place -  Suite 330, Boston,  MA 02111-1307, --
-- USA.  
`
DTraq is dead. Website doesn't exist and xmlezout doesn't provide with COPYING file.

**Comment by mosteo** [comment]
Thanks for the report. Fixed in commit 5ca2e02.
